name: offline_ai_enhancer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.0
  tflite_flutter: ^0.11.0
  image_picker: ^1.0.7
  gal: ^2.2.0 # lightweight, modern gallery saver
  image: ^4.1.7
  shared_preferences: ^2.2.2
  in_app_purchase: ^3.1.13
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0 # for premium look
  lottie: ^3.1.0 # for splash animation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/animations/
